version: "3.8"
networks:
  influxdb:
    external: true

services:
  server:
    build:
      context: ./rest_server/
      dockerfile: docker/Dockerfile
    image:  home-sensor/server
    environment:
      - MAX_WORKERS=1
    volumes:
      - ./rest_server/data:/var/lib/home-sensor
    expose:
      - "8080"
    networks:
      - influxdb
    restart: unless-stopped

  web:
    build:
      context: ./web_client/
      dockerfile: docker/Dockerfile
    image: home-sensor/web
    expose:
      - "8080"
    restart: unless-stopped
    depends_on:
      - server
