version: "3.8"
networks:
  influxdb:
    external: true
  traefik:
    external: true

services:
  server:
    build:
      context: ./rest_server/
      dockerfile: docker/Dockerfile
    image:  home-sensor/server
    environment:
      - MAX_WORKERS=4
    env_file:
      - .env
    volumes:
      - ./rest_server/data:/var/lib/home-sensor
    expose:
      - "80"
    networks:
      - influxdb
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home-sensor-server.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.home-sensor-server.entrypoints=web"
      - "traefik.http.routers.home-sensor-server-secure.rule=Host(`home-sensor.home`) && PathPrefix(`/api`)"
      - "traefik.http.routers.home-sensor-server-secure.entrypoints=websecure"
      - "traefik.http.routers.home-sensor-server-secure.tls"
      - "traefik.docker.network=traefik"
    restart: unless-stopped

  web:
    build:
      context: ./web_client/
      dockerfile: docker/Dockerfile
    image: home-sensor/web
    expose:
      - "8080"
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home-sensor-web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.home-sensor-web.entrypoints=web"
      - "traefik.http.routers.home-sensor-web-secure.rule=Host(`home-sensor.home`) && PathPrefix(`/`)"
      - "traefik.http.routers.home-sensor-web-secure.entrypoints=websecure"
      - "traefik.http.routers.home-sensor-web-secure.tls"
      - "traefik.docker.network=traefik"
    depends_on:
      - server

